/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ConsentRegistry__factory } from "./ConsentRegistry__factory";
export { HealthRecords__factory } from "./HealthRecords__factory";
