/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ConsentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accessRequests"
      | "allowsTransfers"
      | "computeHash"
      | "getGrant"
      | "grantAccess"
      | "grants"
      | "isGrantValid"
      | "recordUpload"
      | "redeemAccess"
      | "requestAccess"
      | "revokeAccess"
      | "setTransferPreference"
      | "transferAccess"
      | "uploadedCids"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessGranted"
      | "AccessRedeemed"
      | "AccessRequested"
      | "AccessRevoked"
      | "AccessTransferred"
      | "UploadRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "accessRequests",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allowsTransfers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "computeHash", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getGrant",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccess",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grants",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isGrantValid",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordUpload",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemAccess",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestAccess",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTransferPreference",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAccess",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "uploadedCids",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "accessRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowsTransfers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGrant", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grants", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isGrantValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordUpload",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTransferPreference",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uploadedCids",
    data: BytesLike
  ): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [
    cidHash: BytesLike,
    patientIdHash: BytesLike,
    hospitalIdHash: BytesLike,
    expiry: BigNumberish,
    ts: BigNumberish
  ];
  export type OutputTuple = [
    cidHash: string,
    patientIdHash: string,
    hospitalIdHash: string,
    expiry: bigint,
    ts: bigint
  ];
  export interface OutputObject {
    cidHash: string;
    patientIdHash: string;
    hospitalIdHash: string;
    expiry: bigint;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessRedeemedEvent {
  export type InputTuple = [
    cidHash: BytesLike,
    patientIdHash: BytesLike,
    hospitalIdHash: BytesLike,
    actor: AddressLike,
    ts: BigNumberish
  ];
  export type OutputTuple = [
    cidHash: string,
    patientIdHash: string,
    hospitalIdHash: string,
    actor: string,
    ts: bigint
  ];
  export interface OutputObject {
    cidHash: string;
    patientIdHash: string;
    hospitalIdHash: string;
    actor: string;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessRequestedEvent {
  export type InputTuple = [
    cidHash: BytesLike,
    patientIdHash: BytesLike,
    requesterHash: BytesLike,
    ts: BigNumberish
  ];
  export type OutputTuple = [
    cidHash: string,
    patientIdHash: string,
    requesterHash: string,
    ts: bigint
  ];
  export interface OutputObject {
    cidHash: string;
    patientIdHash: string;
    requesterHash: string;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessRevokedEvent {
  export type InputTuple = [
    cidHash: BytesLike,
    patientIdHash: BytesLike,
    hospitalIdHash: BytesLike,
    ts: BigNumberish
  ];
  export type OutputTuple = [
    cidHash: string,
    patientIdHash: string,
    hospitalIdHash: string,
    ts: bigint
  ];
  export interface OutputObject {
    cidHash: string;
    patientIdHash: string;
    hospitalIdHash: string;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessTransferredEvent {
  export type InputTuple = [
    cidHash: BytesLike,
    patientIdHash: BytesLike,
    fromHospitalHash: BytesLike,
    toHospitalHash: BytesLike,
    ts: BigNumberish
  ];
  export type OutputTuple = [
    cidHash: string,
    patientIdHash: string,
    fromHospitalHash: string,
    toHospitalHash: string,
    ts: bigint
  ];
  export interface OutputObject {
    cidHash: string;
    patientIdHash: string;
    fromHospitalHash: string;
    toHospitalHash: string;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UploadRecordedEvent {
  export type InputTuple = [
    cidHash: BytesLike,
    patientIdHash: BytesLike,
    hospitalIdHash: BytesLike,
    actor: AddressLike,
    ts: BigNumberish
  ];
  export type OutputTuple = [
    cidHash: string,
    patientIdHash: string,
    hospitalIdHash: string,
    actor: string,
    ts: bigint
  ];
  export interface OutputObject {
    cidHash: string;
    patientIdHash: string;
    hospitalIdHash: string;
    actor: string;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConsentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ConsentRegistry;
  waitForDeployment(): Promise<this>;

  interface: ConsentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accessRequests: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike, arg2: BigNumberish],
    [
      [string, bigint, boolean] & {
        requesterHash: string;
        requestedAt: bigint;
        pending: boolean;
      }
    ],
    "view"
  >;

  allowsTransfers: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  computeHash: TypedContractMethod<[input: string], [string], "view">;

  getGrant: TypedContractMethod<
    [cidHash: BytesLike, patientIdHash: BytesLike, hospitalIdHash: BytesLike],
    [
      [boolean, bigint, bigint] & {
        active: boolean;
        expiry: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  grantAccess: TypedContractMethod<
    [
      cidHash: BytesLike,
      patientIdHash: BytesLike,
      hospitalIdHash: BytesLike,
      expiry: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  grants: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike, arg2: BytesLike],
    [
      [string, bigint, boolean, bigint] & {
        hospitalIdHash: string;
        expiry: bigint;
        active: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  isGrantValid: TypedContractMethod<
    [cidHash: BytesLike, patientIdHash: BytesLike, hospitalIdHash: BytesLike],
    [boolean],
    "view"
  >;

  recordUpload: TypedContractMethod<
    [cidHash: BytesLike, patientIdHash: BytesLike, hospitalIdHash: BytesLike],
    [void],
    "nonpayable"
  >;

  redeemAccess: TypedContractMethod<
    [cidHash: BytesLike, patientIdHash: BytesLike, hospitalIdHash: BytesLike],
    [void],
    "nonpayable"
  >;

  requestAccess: TypedContractMethod<
    [cidHash: BytesLike, patientIdHash: BytesLike, requesterHash: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeAccess: TypedContractMethod<
    [cidHash: BytesLike, patientIdHash: BytesLike, hospitalIdHash: BytesLike],
    [void],
    "nonpayable"
  >;

  setTransferPreference: TypedContractMethod<
    [patientIdHash: BytesLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  transferAccess: TypedContractMethod<
    [
      cidHash: BytesLike,
      patientIdHash: BytesLike,
      fromHospitalHash: BytesLike,
      toHospitalHash: BytesLike,
      newExpiry: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  uploadedCids: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accessRequests"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike, arg2: BigNumberish],
    [
      [string, bigint, boolean] & {
        requesterHash: string;
        requestedAt: bigint;
        pending: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "allowsTransfers"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "computeHash"
  ): TypedContractMethod<[input: string], [string], "view">;
  getFunction(
    nameOrSignature: "getGrant"
  ): TypedContractMethod<
    [cidHash: BytesLike, patientIdHash: BytesLike, hospitalIdHash: BytesLike],
    [
      [boolean, bigint, bigint] & {
        active: boolean;
        expiry: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantAccess"
  ): TypedContractMethod<
    [
      cidHash: BytesLike,
      patientIdHash: BytesLike,
      hospitalIdHash: BytesLike,
      expiry: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grants"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike, arg2: BytesLike],
    [
      [string, bigint, boolean, bigint] & {
        hospitalIdHash: string;
        expiry: bigint;
        active: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isGrantValid"
  ): TypedContractMethod<
    [cidHash: BytesLike, patientIdHash: BytesLike, hospitalIdHash: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordUpload"
  ): TypedContractMethod<
    [cidHash: BytesLike, patientIdHash: BytesLike, hospitalIdHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "redeemAccess"
  ): TypedContractMethod<
    [cidHash: BytesLike, patientIdHash: BytesLike, hospitalIdHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestAccess"
  ): TypedContractMethod<
    [cidHash: BytesLike, patientIdHash: BytesLike, requesterHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeAccess"
  ): TypedContractMethod<
    [cidHash: BytesLike, patientIdHash: BytesLike, hospitalIdHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTransferPreference"
  ): TypedContractMethod<
    [patientIdHash: BytesLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferAccess"
  ): TypedContractMethod<
    [
      cidHash: BytesLike,
      patientIdHash: BytesLike,
      fromHospitalHash: BytesLike,
      toHospitalHash: BytesLike,
      newExpiry: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "uploadedCids"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "AccessRedeemed"
  ): TypedContractEvent<
    AccessRedeemedEvent.InputTuple,
    AccessRedeemedEvent.OutputTuple,
    AccessRedeemedEvent.OutputObject
  >;
  getEvent(
    key: "AccessRequested"
  ): TypedContractEvent<
    AccessRequestedEvent.InputTuple,
    AccessRequestedEvent.OutputTuple,
    AccessRequestedEvent.OutputObject
  >;
  getEvent(
    key: "AccessRevoked"
  ): TypedContractEvent<
    AccessRevokedEvent.InputTuple,
    AccessRevokedEvent.OutputTuple,
    AccessRevokedEvent.OutputObject
  >;
  getEvent(
    key: "AccessTransferred"
  ): TypedContractEvent<
    AccessTransferredEvent.InputTuple,
    AccessTransferredEvent.OutputTuple,
    AccessTransferredEvent.OutputObject
  >;
  getEvent(
    key: "UploadRecorded"
  ): TypedContractEvent<
    UploadRecordedEvent.InputTuple,
    UploadRecordedEvent.OutputTuple,
    UploadRecordedEvent.OutputObject
  >;

  filters: {
    "AccessGranted(bytes32,bytes32,bytes32,uint256,uint256)": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "AccessRedeemed(bytes32,bytes32,bytes32,address,uint256)": TypedContractEvent<
      AccessRedeemedEvent.InputTuple,
      AccessRedeemedEvent.OutputTuple,
      AccessRedeemedEvent.OutputObject
    >;
    AccessRedeemed: TypedContractEvent<
      AccessRedeemedEvent.InputTuple,
      AccessRedeemedEvent.OutputTuple,
      AccessRedeemedEvent.OutputObject
    >;

    "AccessRequested(bytes32,bytes32,bytes32,uint256)": TypedContractEvent<
      AccessRequestedEvent.InputTuple,
      AccessRequestedEvent.OutputTuple,
      AccessRequestedEvent.OutputObject
    >;
    AccessRequested: TypedContractEvent<
      AccessRequestedEvent.InputTuple,
      AccessRequestedEvent.OutputTuple,
      AccessRequestedEvent.OutputObject
    >;

    "AccessRevoked(bytes32,bytes32,bytes32,uint256)": TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;
    AccessRevoked: TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;

    "AccessTransferred(bytes32,bytes32,bytes32,bytes32,uint256)": TypedContractEvent<
      AccessTransferredEvent.InputTuple,
      AccessTransferredEvent.OutputTuple,
      AccessTransferredEvent.OutputObject
    >;
    AccessTransferred: TypedContractEvent<
      AccessTransferredEvent.InputTuple,
      AccessTransferredEvent.OutputTuple,
      AccessTransferredEvent.OutputObject
    >;

    "UploadRecorded(bytes32,bytes32,bytes32,address,uint256)": TypedContractEvent<
      UploadRecordedEvent.InputTuple,
      UploadRecordedEvent.OutputTuple,
      UploadRecordedEvent.OutputObject
    >;
    UploadRecorded: TypedContractEvent<
      UploadRecordedEvent.InputTuple,
      UploadRecordedEvent.OutputTuple,
      UploadRecordedEvent.OutputObject
    >;
  };
}
