/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface HealthRecordsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getRecord"
      | "grants"
      | "isGrantValid"
      | "recordGrant"
      | "records"
      | "revokeGrant"
      | "setRecord"
      | "viewGrant"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "GrantRecorded" | "GrantRevoked" | "RecordUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getRecord",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grants",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isGrantValid",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordGrant",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "records",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeGrant",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "setRecord", values: [string]): string;
  encodeFunctionData(
    functionFragment: "viewGrant",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grants", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isGrantValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordGrant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "records", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeGrant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRecord", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "viewGrant", data: BytesLike): Result;
}

export namespace GrantRecordedEvent {
  export type InputTuple = [
    cid: string,
    granter: AddressLike,
    granteePubkey: string,
    expiryTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    cid: string,
    granter: string,
    granteePubkey: string,
    expiryTimestamp: bigint
  ];
  export interface OutputObject {
    cid: string;
    granter: string;
    granteePubkey: string;
    expiryTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GrantRevokedEvent {
  export type InputTuple = [
    cid: string,
    granter: AddressLike,
    granteePubkey: string
  ];
  export type OutputTuple = [
    cid: string,
    granter: string,
    granteePubkey: string
  ];
  export interface OutputObject {
    cid: string;
    granter: string;
    granteePubkey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordUpdatedEvent {
  export type InputTuple = [patient: AddressLike, cid: string];
  export type OutputTuple = [patient: string, cid: string];
  export interface OutputObject {
    patient: string;
    cid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HealthRecords extends BaseContract {
  connect(runner?: ContractRunner | null): HealthRecords;
  waitForDeployment(): Promise<this>;

  interface: HealthRecordsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRecord: TypedContractMethod<[patient: AddressLike], [string], "view">;

  grants: TypedContractMethod<
    [arg0: string, arg1: string],
    [
      [boolean, bigint, string, bigint] & {
        isActive: boolean;
        expiryTimestamp: bigint;
        granter: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  isGrantValid: TypedContractMethod<
    [cid: string, granteePubkey: string],
    [boolean],
    "view"
  >;

  recordGrant: TypedContractMethod<
    [cid: string, granteePubkey: string, expiryTimestamp: BigNumberish],
    [void],
    "nonpayable"
  >;

  records: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  revokeGrant: TypedContractMethod<
    [cid: string, granteePubkey: string],
    [void],
    "nonpayable"
  >;

  setRecord: TypedContractMethod<[cid: string], [void], "nonpayable">;

  viewGrant: TypedContractMethod<
    [cid: string, granteePubkey: string],
    [
      [boolean, bigint, string] & {
        isActive: boolean;
        expiryTimestamp: bigint;
        granter: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<[patient: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "grants"
  ): TypedContractMethod<
    [arg0: string, arg1: string],
    [
      [boolean, bigint, string, bigint] & {
        isActive: boolean;
        expiryTimestamp: bigint;
        granter: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isGrantValid"
  ): TypedContractMethod<
    [cid: string, granteePubkey: string],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordGrant"
  ): TypedContractMethod<
    [cid: string, granteePubkey: string, expiryTimestamp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "records"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "revokeGrant"
  ): TypedContractMethod<
    [cid: string, granteePubkey: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRecord"
  ): TypedContractMethod<[cid: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "viewGrant"
  ): TypedContractMethod<
    [cid: string, granteePubkey: string],
    [
      [boolean, bigint, string] & {
        isActive: boolean;
        expiryTimestamp: bigint;
        granter: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "GrantRecorded"
  ): TypedContractEvent<
    GrantRecordedEvent.InputTuple,
    GrantRecordedEvent.OutputTuple,
    GrantRecordedEvent.OutputObject
  >;
  getEvent(
    key: "GrantRevoked"
  ): TypedContractEvent<
    GrantRevokedEvent.InputTuple,
    GrantRevokedEvent.OutputTuple,
    GrantRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RecordUpdated"
  ): TypedContractEvent<
    RecordUpdatedEvent.InputTuple,
    RecordUpdatedEvent.OutputTuple,
    RecordUpdatedEvent.OutputObject
  >;

  filters: {
    "GrantRecorded(string,address,string,uint256)": TypedContractEvent<
      GrantRecordedEvent.InputTuple,
      GrantRecordedEvent.OutputTuple,
      GrantRecordedEvent.OutputObject
    >;
    GrantRecorded: TypedContractEvent<
      GrantRecordedEvent.InputTuple,
      GrantRecordedEvent.OutputTuple,
      GrantRecordedEvent.OutputObject
    >;

    "GrantRevoked(string,address,string)": TypedContractEvent<
      GrantRevokedEvent.InputTuple,
      GrantRevokedEvent.OutputTuple,
      GrantRevokedEvent.OutputObject
    >;
    GrantRevoked: TypedContractEvent<
      GrantRevokedEvent.InputTuple,
      GrantRevokedEvent.OutputTuple,
      GrantRevokedEvent.OutputObject
    >;

    "RecordUpdated(address,string)": TypedContractEvent<
      RecordUpdatedEvent.InputTuple,
      RecordUpdatedEvent.OutputTuple,
      RecordUpdatedEvent.OutputObject
    >;
    RecordUpdated: TypedContractEvent<
      RecordUpdatedEvent.InputTuple,
      RecordUpdatedEvent.OutputTuple,
      RecordUpdatedEvent.OutputObject
    >;
  };
}
