/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ConsentRegistry } from "./ConsentRegistry";
export type { HealthRecords } from "./HealthRecords";
export * as factories from "./factories";
export { ConsentRegistry__factory } from "./factories/ConsentRegistry__factory";
export { HealthRecords__factory } from "./factories/HealthRecords__factory";
